//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashCount()
        {
            this.CashImage = new HashSet<CashImage>();
        }
    
        public int FK_workerID { get; set; }
        public int FK_machineID { get; set; }
        public int FK_roundID { get; set; }
        public int countID { get; set; }
        public int countResult { get; set; }
        public int countDoubleResult { get; set; }
        public bool resultJudge { get; set; }
        public System.DateTime operatTime { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Round Round { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashImage> CashImage { get; set; }
    }
}
